server:
  port: ${SPRING_CONTAINER_PORT:8085}
  servlet:
    context-path: /api

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/userdb?createDatabaseIfNotExist=true&enabledTLSProtocols=TLSv1.2&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        format_sql: false
        globally_quoted_identifiers: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
management:
  endpoints:
    web:
      exposure:
        include: 'health, prometheus'
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true